version: '3.8'
services:
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: admin
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  redis:
    image: redis
    ports:
      - "6379:6379"

  app1:
    depends_on:
      - mongo
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      MONGO_USER: admin
      MONGO_PASSWORD: password
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DB: genesis-books
    ports:
      - "8000:8000"
    stdin_open: true

  app2:
    depends_on:
      - mongo
    build:
      context: .
      dockerfile: Dockerfile.worker
    ports:
      - "8001:8001"
    stdin_open: true
    command:
      -